depo/config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :orders

  resources :line_items

  devise_for :users
  get 'admin/index'

  get "store/index"
  resources :products

  get "mycart/index" 

  get "mycart/list"
   
   post "mycart/delete"

  root 'store#index', as: 'store'

end

depo/app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
  belongs_to :order
  
    def totalprice(current_user)
    	  
    	   @totalprice = 0
    	    line_items = LineItem.all 

    	  current_user.line_items.where(:status => 0).each do |m|
    	 @totalprice += m.product.price * m.quantity

    	
           end

           @totalprice
     end
 
end

depo/app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_line_item, only: [:show, :edit, :update, :destroy]
  
  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all.where("status = ?", 0)
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create

     @product = Product.find(params[:product_id])

       @line_item = @product.add_product(@product.id, current_user)
                 #@line_item = current_user.line_items.build(product: product)
              
              
      respond_to do |format|
      if @line_item.save

        format.html { redirect_to @line_item, notice: ' item was successfully added to the cart.' }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
      current_user.line_items.where(:status => 0).destroy_all
      respond_to do |format|
      format.html { redirect_to store_url,notice: 'Your cart is currently empty' }
      format.json { head :no_content }
end
 end

  
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id, :user_id)
    end
end

depo/app/helpers/line_items_helper.rb
module LineItemsHelper
	
end

depo/app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

depo/app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

depo/app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product %></td>
        <td><%= line_item.user %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

depo/app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

depo/app/views/line_items/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>
 <h2>Your Cart</h2>
 <table>
  <thead>
    <tr>
      <th>productName</th> 
      <th>quantity</th>
      <th>price</th>
      <th> option </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
     <% @arr = Array.new %>
       <% current_user.line_items.all.where("status = ?", 0).each do |item| %>
      <tr>
        <td><%=item.product.title %></td>
        <td><%=item.quantity %></td>
        <td><%=  number_to_currency(item.product.price) %></td>
        
        <% @arr << item.product.price * item.quantity %>
       <td><%= link_to 'remove',mycart_delete_path(:item_id => item.id), method: :post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

    <table>
 <% $sum = @arr.sum %>
      <tr class="total_line">
  
      <td colspan="2">Total</td>

      <td class="total_cell"><%= number_to_currency($sum) %></td>

     </tr>

 </table>
 	 



   <%= button_to "Checkout", new_order_path, :method => :get %> <br/>
  <%= button_to 'Empty cart', @line_item, :method => :delete,data: { confirm: 'Are you sure?' } %> &nbsp;
   <%= button_to 'continu_shopping', '/', :method => :get %>